apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: 147ajt369/report
          envFrom:
            - configMapRef:
                name: report-configmap
            - secretRef:
                name: report-secret